dataset:
  type: AnomalyDetectionDataset
  parameters:
    dataset_root: ./build/CATS
    csv_file: https://zenodo.org/records/8338435/files/data.csv
    split_seed: 12345
    split_fraction_test: 0.1
    inference_batch_size: 1
    # Reduce dataset to speedup the AutoML flow
    reduce_dataset: 0.1
automl:
  type: AutoPyTorchML
  parameters:
    output_directory: ./build/cnn-automl2
    time_limit: 15
    use_models:
      - PyTorchAnomalyDetectionCNN:
          conv_stride:
            item_range: [1, 1]
          conv_dilation:
            item_range: [1, 1]
          pool_stride:
            item_range: [1, 1]
          pool_dilation:
            item_range: [1, 1]
    n_best_models: 5
    # AutoPyTorch specific options
    optimize_metric: f1
    budget_type: epochs
    min_budget: 1
    max_budget: 5
    # To use GPU uncomment line below
    # use_cuda: True
optimizers:
- type: TFLiteCompiler
  parameters:
    target: int8
    compiled_model_path: ./build/cnn_int8.tflite
    inference_input_type: int8
    inference_output_type: int8
