platform:
  type: ZephyrPlatform
  parameters:
    name: max32690evkit/max32690/m4
    simulated: false
    openocd_path: /mnt/hdd_0/Workspace/ad-openocd-2/bin/openocd
    uart_log_port: /dev/ttyUSB0
    zephyr_build_path: ./build/zephyr-workspace/kenning-zephyr-runtime/build
# runtime_builder:
#   type: ZephyrRuntimeBuilder
#   parameters:
#     workspace: ./build/zephyr-workspace/kenning-zephyr-runtime
#     run_west_update: false
#     output_path: ./build/kzr-output
model_wrapper:
  type: PyTorchAnomalyDetectionVAE
  parameters:
    model_path: build/vae_small.pth
dataset:
  type: AnomalyDetectionDataset
  parameters:
    dataset_root: build/AnomalyDetectionDataset
    csv_file: https://zenodo.org/records/8338435/files/data.csv
optimizers:
- type: TFLiteCompiler
  parameters:
    target: default
    compiled_model_path: ./build/vae_fp32.tflite
    inference_input_type: float32
    inference_output_type: float32

