image: $CI_BASE_IMAGE

.ace: &ace
    tags: ['ace-x86_64']

.common_only: &common_only
    only:
        - main
        - dev
        - merge_requests

variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
    DOCS_DIR: './docs'

stages:
    - lint
    - prepare
    - tests
    - docs
    - docs-deploy

pre-commit:
    image: $CI_LINT_IMAGE
    <<: *ace
    <<: *common_only
    stage: lint
    script:
        - pre-commit run --all-files || (echo "pre-commit changes:" && git diff && false)

pytest:
    <<: *ace
    <<: *common_only
    stage: tests
    script:
        - /scripts/prepare_environment.sh .
        - pip uninstall -y pipeline_manager
        - pip install -e ".[test,pipeline_manager]"
        - pip install -e ".[llm]"
        - wget https://builds.renode.io/renode-latest.pkg.tar.xz
        - export PYRENODE_PKG=$(realpath renode-latest.pkg.tar.xz)
        - PYTHONPATH=$(pwd):$PYTHONPATH timeout --preserve-status -s INT -k 58m 55m pytest kenning -m "(not docs_gallery) and (not docs)" -n=auto --cov=kenning --cov-report=html
    artifacts:
        paths:
            - log.json
            - log_docs/*.log
            - $DOCS_DIR/source/generated/coverage/*
        when: always

.pytest-docs: &pytest-docs
    image: $CI_MINIMAL_IMAGE
    stage: tests
    script:
        - /scripts/prepare_environment.sh .
        # Prepare Docker
        - /scripts/prepare_docker.sh
        - trap "kill $(cat /var/run/docker.pid)" EXIT
        - pip install -e ".[test]"
        - PYTHONPATH=$(pwd):$PYTHONPATH pytest kenning/tests/docs/test_snippets.py -m $TESTS_SCOPE -n=4 --test-docs-log-dir $TESTS_SCOPE
    artifacts:
        paths:
            - log.json
            - $TESTS_SCOPE/*.log
        when: always

.nox-prepare-deps:
    <<: *ace
    <<: *common_only
    image: $CI_NOX_IMAGE
    stage: prepare
    script:
        - for v in $PY_VERSIONS; do nox -s "get_deps-${v}(device='${DEVICE}')"; done
    artifacts:
        paths:
            - "kenning-deps"
        expire_in: 1 day

nox-prepare-deps-any-schedule:
    extends: .nox-prepare-deps
    variables:
        DEVICE: any
    only:
        - schedules

nox-prepare-deps-any:
    extends: .nox-prepare-deps
    variables:
        DEVICE: any
    when: manual

.nox-pytest:
    <<: *ace
    <<: *common_only
    image: $CI_NOX_IMAGE
    stage: tests
    script:
        - /scripts/prepare_environment.sh .
        - /scripts/prepare_deps.sh nox-prepare-deps-any nox-prepare-deps-any-schedule
        - export NOX_PYTEST_EXPLICIT_DOWNLOAD=y
        - nox -vs "run_pytest-${PY_VERSION}(device='any')"
    artifacts:
        paths:
            - pytest-reports
            - requirements

nox-pytest-3.9:
    extends: .nox-pytest
    variables:
        PY_VERSION: "3.9"

nox-pytest-3.10:
    extends: .nox-pytest
    variables:
        PY_VERSION: "3.10"

nox-pytest-3.11:
    extends: .nox-pytest
    variables:
        PY_VERSION: "3.11"

nox-gallery:
    <<: *ace
    <<: *common_only
    image: $CI_NOX_IMAGE
    stage: tests
    script:
        - /scripts/prepare_environment.sh .
        - /scripts/prepare_docker.sh
        - trap "kill $(cat /var/run/docker.pid)" EXIT
        - nox -vs run_gallery_tests
    when: manual

docs-tests:
    <<: *ace
    variables:
        TESTS_SCOPE: 'docs'
    only:
        refs:
            - main
            - dev
    <<: *pytest-docs

docs-tests-manual:
    <<: *ace
    variables:
        TESTS_SCOPE: 'docs'
    except:
        refs:
            - main
            - dev
    only:
        refs:
            - merge_requests
    <<: *pytest-docs
    when: manual

docs-gallery-tests:
    <<: *ace
    variables:
        TESTS_SCOPE: 'docs_gallery'
    only:
        refs:
            - main
            - dev
    <<: *pytest-docs

docs-gallery-tests-manual:
    <<: *ace
    variables:
        TESTS_SCOPE: 'docs_gallery'
    except:
        refs:
            - main
            - dev
    only:
        refs:
            - merge_requests
    <<: *pytest-docs
    when: manual

sample-compilation:
    <<: *ace
    <<: *common_only
    stage: tests
    script:
        - /scripts/prepare_environment.sh .
        - ./scripts/tvm-tensorflow-classification-cpu.sh
    artifacts:
        paths:
            - build/local-cpu-tvm-tensorflow-classification.json
            - docs/source/generated

sample-pipeline-optimization:
    <<: *ace
    <<: *common_only
    stage: tests
    script:
        - /scripts/prepare_environment.sh .
        - ./scripts/optimization-tflite-tvm-tensorflow-magic-wand.sh
    artifacts:
        paths:
            - build/

sample-client-server-scenario:
    <<: *ace
    <<: *common_only
    stage: tests
    script:
        - /scripts/prepare_environment.sh .
        - apt-get update && apt-get install -y procps
        - ./scripts/json-tflite-tvm-classification-server.sh &
        - PID=$!
        - ./scripts/json-tflite-tvm-classification-client.sh || CLIENT_RET=$?
        - kill -SIGINT $(pgrep -f "kenning server") && wait $PID || SERVER_RET=$?
        - exit $((CLIENT_RET | SERVER_RET))
    artifacts:
        paths:
            - build/
    allow_failure: false

docs:
    image: $CI_DOCS_IMAGE
    <<: *ace
    <<: *common_only
    stage: docs
    dependencies:
        - pytest
        - sample-compilation
    script:
        - cd $DOCS_DIR
        - echo -en "\nhtml_js_files = [ '$ANNOTANT' ]" >> source/conf.py
        - make html latexpdf
        - cp build/latex/*.pdf build/html/
        - tar cf $CI_DOCS_ARCHIVE -C build/html/ .
        - mv $CI_DOCS_ARCHIVE ..
    artifacts:
        paths:
            - $DOCS_DIR/build/html
            - $DOCS_DIR/build/latex/*.pdf
            - $CI_DOCS_ARCHIVE

linkcheck:
    image: $CI_DOCS_IMAGE
    <<: *ace
    <<: *common_only
    stage: docs
    dependencies:
        - sample-compilation
    script:
        - cd $DOCS_DIR
        - make linkcheck
    allow_failure: true

docs-deploy:
    <<: *common_only
    image: $CI_DOCS_DOCKER_IMAGE
    dependencies:
        - docs
    variables:
        GIT_STRATEGY: none
    stage: docs-deploy
    tags:
        - docs
    script:
        - echo 'Deploying docs'
    artifacts:
        paths:
            - $CI_DOCS_ARCHIVE
