image: $CI_IMAGE

.ace: &ace
    tags: ['ace-x86_64']

.common_only: &common_only
    only:
        - main
        - dev
        - merge_requests

variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - lint
    - tests
    - docs
    - docs-deploy

pre-commit:
    <<: *ace
    <<: *common_only
    stage: lint
    script:
        - pre-commit run --all-files
    allow_failure: false

pytest:
    <<: *ace
    <<: *common_only
    stage: tests
    variables:
        KENNING_DOCS_VENV: .docs_venv
    before_script:
        - mkdir -p build
        - ln -s /data/* build/
        - ln -s /data/COCODataset2017 build/VisualWakeWordsDataset
        - pip install --no-deps -e .
        - python -m venv --system-site-packages $KENNING_DOCS_VENV
    script:
        - PYTHONPATH=$(pwd):$PYTHONPATH pytest -ra kenning -k "not docs_gallery" -n=auto --dist=loadgroup --order-dependencies --color=yes --report-log=log.json --test-docs-log-dir log_docs -vvl
    artifacts:
        paths:
            - log.json
            - log_docs/*.log
        when: always
    allow_failure: false

pytest-gallery:
    <<: *ace
    <<: *common_only
    stage: tests
    before_script:
        # Prepare Docker
        - apt-get update --allow-releaseinfo-change -y > /dev/null 2> /dev/null
        - apt-get -qqy --no-install-recommends install docker.io cgroupfs-mount crun fuse-overlayfs pigz ca-certificates > /dev/null
        - cgroupfs-mount
        - dockerd -s fuse-overlayfs --add-runtime=crun=/usr/bin/crun --default-runtime=crun --config-file="" > /dev/null 2> /dev/null &
        - while ! test -S /var/run/docker.sock; do echo "Waiting for Docker..." && sleep 1; done; docker info
        - trap "kill $(cat /var/run/docker.pid)" EXIT
        # Do not use installed TVM
        - rm /usr/lib/libtvm.so /usr/lib/libtvm_runtime.so
    script:
        - PYTHONPATH=$(pwd):$PYTHONPATH pytest -ra kenning/tests/docs/test_snippets.py -k docs_gallery -n=4 --dist=loadgroup --order-dependencies --color=yes --report-log=log.json --test-docs-log-dir log_gallery -vvl
    artifacts:
        paths:
            - log_gallery/*.log
        when: always
    allow_failure: false

sample-compilation:
    <<: *ace
    <<: *common_only
    stage: tests
    script:
        - mkdir build
        - ln -s /data/PetDataset build/PetDataset
        - sed -i '/download-dataset/d' ./scripts/tvm-tensorflow-classification-cpu.sh
        - ./scripts/tvm-tensorflow-classification-cpu.sh
    artifacts:
        paths:
            - build/local-cpu-tvm-tensorflow-classification.json
            - docs/source/generated
    allow_failure: false

sample-pipeline-optimization:
    <<: *ace
    <<: *common_only
    stage: tests
    script:
        - mkdir -p build
        - ln -s /data/MagicWandDataset build/MagicWandDataset
        - ./scripts/optimization-tflite-tvm-tensorflow-magic-wand.sh
    artifacts:
        paths:
            - build/
    allow_failure: false

sample-client-server-scenario:
    <<: *ace
    <<: *common_only
    stage: tests
    script:
        - apt-get update && apt-get install -y procps
        - mkdir -p build
        - ln -s /data/PetDataset build/PetDataset
        - sed -i 's/10.9.8.7/localhost/g' ./scripts/jsonconfigs/tflite-tvm-classification-client-server.json
        - ./scripts/json-tflite-tvm-classification-server.sh &
        - PID=$!
        - ./scripts/json-tflite-tvm-classification-client.sh || CLIENT_RET=$?
        - kill -SIGINT $(pgrep -f "kenning server") && wait $PID || SERVER_RET=$?
        - exit $((CLIENT_RET | SERVER_RET))
    artifacts:
        paths:
            - build/
    allow_failure: false

docs:
    <<: *ace
    <<: *common_only
    stage: docs
    dependencies:
        - sample-compilation
    variables:
        DOCS_DIR: './docs'
    script:
        - cd $DOCS_DIR
        - echo -en "\nhtml_js_files = [ '$ANNOTANT' ]" >> source/conf.py
        - make html latexpdf
        - cp build/latex/*.pdf build/html/
        - tar cf $CI_DOCS_ARCHIVE -C build/html/ .
        - mv $CI_DOCS_ARCHIVE ..
    artifacts:
        paths:
            - $DOCS_DIR/build/html
            - $DOCS_DIR/build/latex/*.pdf
            - $CI_DOCS_ARCHIVE
    allow_failure: false

linkcheck:
    <<: *ace
    <<: *common_only
    stage: docs
    dependencies:
        - sample-compilation
    variables:
        DOCS_DIR: './docs'
    script:
        - cd $DOCS_DIR
        - make linkcheck
    allow_failure: true

docs-deploy:
    <<: *common_only
    image: $CI_DOCS_DOCKER_IMAGE
    dependencies:
        - docs
    variables:
        GIT_STRATEGY: none
    stage: docs-deploy
    tags:
        - docs
    script:
        - echo 'Deploying docs'
    artifacts:
        paths:
            - $CI_DOCS_ARCHIVE
    allow_failure: false
