image: $CI_IMAGE

variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - lint
    - tests
    - docs
    - docs-deploy

flake8:
    stage: lint
    script:
        - flake8 .
    allow_failure: false

pytest:
    stage: tests
    script:
        - mkdir -p build
        - cp -r /data/* build/
        - PYTHONPATH=$(pwd):$PYTHONPATH pytest -ra kenning -n=auto --dist=loadgroup --color=yes --report-log=log.json
    artifacts:
        paths:
            - log.json
        when: always
    allow_failure: false

onnx-conversions:
    stage: tests
    script:
        - ./scripts/onnxconversions.sh
        - mkdir -p docs/source/generated
        - cp build/onnx-support.md docs/source/generated/onnx-support.md
    artifacts:
        paths:
            - docs/source/generated
    allow_failure: false

sample-compilation:
    stage: tests
    script:
        - mkdir build
        - ln -s /pet-dataset build/pet-dataset
        - sed -i '/download-dataset/d' ./scripts/tvm-tensorflow-classification-cpu.sh
        - ./scripts/tvm-tensorflow-classification-cpu.sh
    artifacts:
        paths:
            - build/local-cpu-tvm-tensorflow-classification.json
            - docs/source/generated
    allow_failure: false

sample-pipeline-optimization:
    stage: tests
    script:
        - mkdir build
        - ln -s /pet-dataset build/pet-dataset
        - ./scripts/optimization-tflite-tvm-tensorflow-pet-dataset.sh
    artifacts:
        paths:
            - build/
    allow_failure: false

docs:
    stage: docs
    dependencies:
        - onnx-conversions
        - sample-compilation
    variables:
        DOCS_DIR: './docs'
    script:
        - cd $DOCS_DIR
        - make html latexpdf
        - cp build/latex/*.pdf build/html/
        - tar cf $CI_DOCS_ARCHIVE -C build/html/ .
        - mv $CI_DOCS_ARCHIVE ..
    artifacts:
        paths:
            - $DOCS_DIR/build/html
            - $DOCS_DIR/build/latex/*.pdf
            - $CI_DOCS_ARCHIVE
    allow_failure: false

linkcheck:
    stage: docs
    dependencies:
        - onnx-conversions
        - sample-compilation
    variables:
        DOCS_DIR: './docs'
    script:
        - cd $DOCS_DIR
        - make linkcheck
    allow_failure: true

docs-deploy:
    image: $CI_DOCS_DOCKER_IMAGE
    dependencies:
        - docs
    variables:
        GIT_STRATEGY: none
    stage: docs-deploy
    tags:
        - docs
    script:
        - echo 'Deploying docs'
    artifacts:
        paths:
            - $CI_DOCS_ARCHIVE
    allow_failure: false
