name: Kenning docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  onnxconversion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ build-essential cmake llvm protobuf-compiler libprotoc-dev
          python -m pip install .[tensorflow,torch,mxnet,docs]
          python -m pip install --upgrade tf-models-official~=2.9.1
      - name: Run ONNX conversion tests
        run: |
          ./scripts/onnxconversions.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: onnxconversion
          path: build/onnx-support.md

  inference-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
             gcc g++ build-essential cmake llvm protobuf-compiler \
             libprotoc-dev libtinfo-dev zlib1g-dev libedit-dev libxml2-dev \
             llvm curl wget
          python -m pip install .[tensorflow,docs,tvm]
      - name: Run sample compilation and inference
        run: |
          ./scripts/tvm-tensorflow-classification-cpu.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: inferencetest
          path: docs/source/generated

  docs-generation:
    runs-on: ubuntu-latest
    needs: [onnxconversion,inference-test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install .[docs]
      - name: Generate documentation
        run: |
          cp -r inferencetest docs/source/generated
          cp onnxconversion/onnx-support.md docs/source/generated
          cd docs
          make html
      - uses: actions/upload-artifact@v3
        with:
          name: gh-page
          path: docs/build/html
      - name: Deploy to Github Pages
        if: github.event_name == 'push'
        run: |
          cd docs/build/html
          touch .nojekyll
          git init
          cp ../../../.git/config ./.git/config
          git add .
          git config --local user.email "push@gha"
          git config --local user.name "GHA"
          git commit -am "update ${{ github.sha }}"
          git push -u origin +HEAD:gh-pages
          rm -rf .git
